### PR TITLE
workon.sh fixes

### LINKED ISSUE #667: Fix workon.sh prefix
In [`workon.sh`](https://github.com/faasm/faasm/blob/bfb77185809a03a75113d99fe36b8c58112b7fa8/bin/workon.sh#L88), the `PS1` is updated the new virtual environment. If `workon.sh` is executed multiple times (e.g. when switching between environments), the old environment is kept in this variable, creating large string of virtual envs like this:

```bash
(faasm-exp) (faasm-exp) (faasm) (faasm-exp) (faasm) mmathys@koala9:~/experiment-base$
```

An easy fix could be to change this line to

```
export PS1="(faasm)"
```

### PR DESCRIPTION
**Pull request by mmathys**
closes #667

### CODE REVIEW

File: bin/workon.sh [hunk 1]
```diff
@@ -37,6 +37,12 @@ pushd ${PROJ_ROOT} >> /dev/null
 # Virtualenv
 # ----------------------------
 
+# disable previous environment with `deactivate` if it exists
```
Comment (Shillaker) [inline bin/workon.sh:40]: Bash file comments aren't markdown, so we don't need the backticks around `deactivate`. Comments should also start with a capital letter.

**Review by Shillaker — CHANGES_REQUESTED** [review]

File: bin/workon.sh [hunk 2]
```diff
@@ -13,7 +13,9 @@ if [[ -z "$FAASM_DOCKER" ]]; then
     if [ "$(ps -o comm= -p $$)" = "zsh" ]; then
         THIS_DIR="$( cd "$( dirname "${ZSH_ARGZERO}" )" >/dev/null 2>&1 && pwd )"
     fi
+    echo $THIS_DIR
     PROJ_ROOT="${THIS_DIR}/.."
+    #PROJ_ROOT="${THIS_DIR}/"
```
Comment (Shillaker) [inline bin/workon.sh:18]: We shouldn't commit commented-out code. Is this needed?

**Review by Shillaker — CHANGES_REQUESTED** [review]

**Review by Shillaker — APPROVED** [review]
